alias gcl "git clone"
alias svim "sudo -E nvim"
alias fm "yazi"
alias ranger "yazi"
alias almh "almh.py"
alias cp "cp -r"
alias ts "sudo -E timeshift-gtk"
alias sfm "sudo -E thunar"
alias mpdmusics "ncmpcpp -c ~/.ncmpcpp/config-art"
#alias hyprpanel "ags -b hyprpanel"
alias slvim "sudo -E lvim"
alias cl "clear"
alias l "eza --long --header --icons --git --group-directories-first --all"
alias ls "l -a"
alias gadd "git add ."
alias gcommit "git commit -m"
alias gpush "git push -u origin main"
alias ... "cd ../.."
alias .... "cd ../../.."
alias nix-rebuild "sudo nixos-rebuild switch --flake .#nixy4life"
alias nix-upgrade "sudo nixos-rebuild switch --flake .#nixy4life --upgrade"
alias nix-flake "sudo nix flake update"
alias nix-home "home-manager switch --flake ."
alias home-flake "nix flake update"
alias nix-rollback "sudo nixos-rebuild switch --rollback .#nixy4life"
#alias cd "z"
