alias gcl "git clone"
alias sv "sudo -E nvim"
alias fm "yazi"
alias ranger "yazi"
alias almh "almh.py"
alias cp "cp -r"
alias ts "sudo -E timeshift-gtk"
alias sfm "sudo -E thunar"
alias mpdmusics "ncmpcpp -c ~/.ncmpcpp/config-art"
alias cl "clear"
#alias ls "eza --long --header --icons --git --group-directories-first "
alias ls "lsd"
alias l "ls -la"
alias lt "ls --tree"
alias gadd "git add ."
alias gcommit "git commit -m"
alias gpush "git push -u origin main"
alias ... "cd ../.."
alias .... "cd ../../.."
alias nix-rebuild "nh os switch"
alias nix-update "nh os switch --update"
alias nix-rollback "sudo nixos-rebuild switch --rollback .#shizuru"
alias delete-garbage "sudo nix-collect-garbage -d && nix-collect-garbage -d"
alias x "exit"
alias ff "fastfetch"
alias nf "neofetch"
alias mf "microfetch"
