alias gcl "git clone"
alias sv "sudo -E nvim"
alias fm "yazi"
alias ranger "yazi"
alias almh "almh.py"
alias cp "cp -r"
alias ts "sudo -E timeshift-gtk"
alias sfm "sudo -E thunar"
alias mpdmusics "ncmpcpp -c ~/.ncmpcpp/config-art"
alias cl "cd ~/NixOS-Hyprland"
alias ls "eza --long --header --icons --git --group-directories-first "
#alias ls "lsd"
alias l "ls -a"
alias lt "ls --tree"
alias gadd "git add ."
alias gcommit "git commit -m"
alias gpush "git push -u origin main"
alias ... "cd ../.."
alias .... "cd ../../.."
alias fuck "nh os switch"
alias fucku "nh os switch --update"
alias rollfuck "sudo nixos-rebuild switch --rollback .#shizuru"
alias fuckgc "nh clean all"
alias fuckdit "codium ~/NixOS-Hyprland"
alias x "exit"
alias e "clear"
alias ff "fastfetch"
alias nf "neofetch"
alias mf "microfetch"
alias q "zellij"
#alias hyprpanel "astal -i hyprpanel"

