{
    "allow-lan": true,
    "bind-address": "127.0.0.1",
    "dns": {
        "enable": false,
        "listen": "0.0.0.0:53",
        "nameserver": [
            "8.8.8.8",
            "4.4.4.4"
        ]
    },
    "log-level": "info",
    "mode": "rule",
    "port": 1087,
    "proxies": [
    ],
    "proxy-groups": [
        {
            "interval": 300,
            "name": "PROXY",
            "proxies": [
            ],
            "type": "load-balance",
            "url": "http://www.gstatic.com/generate_204"
        }
    ],
    "rules": [
        "IP-CIDR, 127.0.0.0/8, DIRECT",
        "IP-CIDR, 10.0.0.0/8, DIRECT",
        "IP-CIDR, 172.16.0.0/12, DIRECT",
        "IP-CIDR, 192.168.0.0/16, DIRECT",
        "GEOIP, CN, DIRECT",
        "MATCH, PROXY"
    ],
    "socks-port": 1080
}
